# v1.61.0
run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - .git
    - .github
    - docs
    - test/template

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gochecknoinits
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/jmcarbo/gotemplate
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - whyNoLint
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-keys-type
      - name: time-naming
      - name: var-declaration
      - name: unexported-return
      - name: errorf
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
        - prealloc
    - path: cmd/
      linters:
        - gochecknoinits
    - path: test/
      linters:
        - errcheck
        - unparam